import "server-only";
import { env } from "@/lib/env";
import { getJson as httpJson, trimSlash } from "@/lib/http";
import { mbidFrom, parseAndDedupePlaylists } from "@/lib/listenbrainz/parse";

/**
 * ListenBrainz client — public read endpoints only (no API key needed). We use
 * the per-user *recommendation* playlists (weekly-exploration / weekly-jams /
 * daily-jams, generated by the Troi engine) as Discovery's mixes, then fetch
 * each playlist's tracks as JSPF.
 *
 * Docs: https://listenbrainz.readthedocs.io/en/latest/users/api/playlist.html
 */

const base = () => trimSlash(env.LISTENBRAINZ_URL);

export interface LbPlaylistMeta {
  mbid: string;
  title: string;
  /** Weekly Exploration | Weekly Jams | Daily Jams | Recommended */
  kind: string;
}

export interface LbTrack {
  title: string;
  artist: string;
  recordingMbid?: string;
  durationSecs?: number;
}

const getJson = (path: string): Promise<unknown> => httpJson(`${base()}${path}`);

/**
 * The current recurring mixes (weekly exploration/jams, daily jams). LB returns
 * many historical + misc playlists, so we keep only the newest of each recurring
 * kind and drop the rest.
 */
export async function getRecommendationPlaylists(): Promise<LbPlaylistMeta[]> {
  const user = env.LISTENBRAINZ_USER;
  if (!user) return [];
  const data = (await getJson(
    `/1/user/${encodeURIComponent(user)}/playlists/recommendations?count=25`,
  )) as {
    playlists?: Array<{ playlist?: { identifier?: unknown; title?: unknown; date?: unknown } }>;
  };
  return parseAndDedupePlaylists(Array.isArray(data.playlists) ? data.playlists : []);
}

/** The tracks of a playlist (JSPF). */
export async function getPlaylistTracks(mbid: string): Promise<LbTrack[]> {
  const data = (await getJson(`/1/playlist/${encodeURIComponent(mbid)}`)) as {
    playlist?: {
      track?: Array<{
        title?: unknown;
        creator?: unknown;
        identifier?: unknown;
        duration?: unknown;
      }>;
    };
  };
  const tracks = data.playlist?.track;
  if (!Array.isArray(tracks)) return [];
  return tracks
    .map((t) => ({
      title: typeof t.title === "string" ? t.title : "",
      artist: typeof t.creator === "string" ? t.creator : "",
      recordingMbid: mbidFrom(t.identifier) || undefined,
      // JSPF duration is milliseconds.
      durationSecs: typeof t.duration === "number" ? Math.round(t.duration / 1000) : undefined,
    }))
    .filter((t) => t.title && t.artist);
}
